main:
  - identifier: about
    name: about
    url: about
    weight: 1
  - identifier: archive
    name: archive
    url: archive
    weight: 2
  # - identifier: gallery
  #   name: gallery
  #   url: gallery
  #   weight: 3
  # - parent: gallery
  #   name: cartoon
  #   url: gallery/cartoon
  # - parent: gallery
  #   name: photo
  #   url: gallery/photo
  - identifier: posts
    name: posts
    url: posts
    weight: 4
  # - identifier: notes
  #   name: notes
  #   url: notes
  #   weight: 5
