baseURL: "https://johnhollowell.com/blog/"
languageCode: "en-us"
title: "/dev/random: A bit over everything"
# theme: "ace-doc"
publishdir: "public/"
outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"

enableEmoji: true
enableRobotsTXT: true

# allow raw HTML in .md files to be passed through to the final page
markup:
  goldmark:
    renderer:
      unsafe: true

# pulls information from git commit for modified date and info
enableGitInfo: true
